# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nmlip.ml.v1\"p\n\x0eListingRequest\x12\x12\n\nlisting_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcondition\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\t\"\xa8\x01\n\x0fListingAnalysis\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\t\x12\x18\n\x10policy_violation\x18\x04 \x01(\x08\x12\x17\n\x0fsuggested_price\x18\x05 \x01(\x01\x12\x19\n\x11price_lower_bound\x18\x06 \x01(\x01\x12\x19\n\x11price_upper_bound\x18\x07 \x01(\x01\x32X\n\tMLService\x12K\n\x0e\x41nalyzeListing\x12\x1a.mlip.ml.v1.ListingRequest\x1a\x1b.mlip.ml.v1.ListingAnalysis\"\x00\x42&Z$github.com/vexyruu/mlip/shared/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/vexyruu/mlip/shared/pb;pb'
  _globals['_LISTINGREQUEST']._serialized_start=32
  _globals['_LISTINGREQUEST']._serialized_end=144
  _globals['_LISTINGANALYSIS']._serialized_start=147
  _globals['_LISTINGANALYSIS']._serialized_end=315
  _globals['_MLSERVICE']._serialized_start=317
  _globals['_MLSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
