// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ml_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingRequest) Reset() {
	*x = ListingRequest{}
	mi := &file_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingRequest) ProtoMessage() {}

func (x *ListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingRequest.ProtoReflect.Descriptor instead.
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListingRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ListingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *ListingRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ListingAnalysis struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Brand           string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Product         string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Size            string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	PolicyViolation bool                   `protobuf:"varint,4,opt,name=policy_violation,json=policyViolation,proto3" json:"policy_violation,omitempty"`
	SuggestedPrice  float64                `protobuf:"fixed64,5,opt,name=suggested_price,json=suggestedPrice,proto3" json:"suggested_price,omitempty"`
	PriceLowerBound float64                `protobuf:"fixed64,6,opt,name=price_lower_bound,json=priceLowerBound,proto3" json:"price_lower_bound,omitempty"`
	PriceUpperBound float64                `protobuf:"fixed64,7,opt,name=price_upper_bound,json=priceUpperBound,proto3" json:"price_upper_bound,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListingAnalysis) Reset() {
	*x = ListingAnalysis{}
	mi := &file_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingAnalysis) ProtoMessage() {}

func (x *ListingAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingAnalysis.ProtoReflect.Descriptor instead.
func (*ListingAnalysis) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListingAnalysis) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListingAnalysis) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ListingAnalysis) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ListingAnalysis) GetPolicyViolation() bool {
	if x != nil {
		return x.PolicyViolation
	}
	return false
}

func (x *ListingAnalysis) GetSuggestedPrice() float64 {
	if x != nil {
		return x.SuggestedPrice
	}
	return 0
}

func (x *ListingAnalysis) GetPriceLowerBound() float64 {
	if x != nil {
		return x.PriceLowerBound
	}
	return 0
}

func (x *ListingAnalysis) GetPriceUpperBound() float64 {
	if x != nil {
		return x.PriceUpperBound
	}
	return 0
}

var File_ml_service_proto protoreflect.FileDescriptor

const file_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x10ml_service.proto\x12\n" +
	"mlip.ml.v1\"\xa6\x01\n" +
	"\x0eListingRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\"\x81\x02\n" +
	"\x0fListingAnalysis\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12)\n" +
	"\x10policy_violation\x18\x04 \x01(\bR\x0fpolicyViolation\x12'\n" +
	"\x0fsuggested_price\x18\x05 \x01(\x01R\x0esuggestedPrice\x12*\n" +
	"\x11price_lower_bound\x18\x06 \x01(\x01R\x0fpriceLowerBound\x12*\n" +
	"\x11price_upper_bound\x18\a \x01(\x01R\x0fpriceUpperBound2X\n" +
	"\tMLService\x12K\n" +
	"\x0eAnalyzeListing\x12\x1a.mlip.ml.v1.ListingRequest\x1a\x1b.mlip.ml.v1.ListingAnalysis\"\x00B&Z$github.com/vexyruu/mlip/shared/pb;pbb\x06proto3"

var (
	file_ml_service_proto_rawDescOnce sync.Once
	file_ml_service_proto_rawDescData []byte
)

func file_ml_service_proto_rawDescGZIP() []byte {
	file_ml_service_proto_rawDescOnce.Do(func() {
		file_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)))
	})
	return file_ml_service_proto_rawDescData
}

var file_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_service_proto_goTypes = []any{
	(*ListingRequest)(nil),  // 0: mlip.ml.v1.ListingRequest
	(*ListingAnalysis)(nil), // 1: mlip.ml.v1.ListingAnalysis
}
var file_ml_service_proto_depIdxs = []int32{
	0, // 0: mlip.ml.v1.MLService.AnalyzeListing:input_type -> mlip.ml.v1.ListingRequest
	1, // 1: mlip.ml.v1.MLService.AnalyzeListing:output_type -> mlip.ml.v1.ListingAnalysis
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_service_proto_init() }
func file_ml_service_proto_init() {
	if File_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_service_proto_goTypes,
		DependencyIndexes: file_ml_service_proto_depIdxs,
		MessageInfos:      file_ml_service_proto_msgTypes,
	}.Build()
	File_ml_service_proto = out.File
	file_ml_service_proto_goTypes = nil
	file_ml_service_proto_depIdxs = nil
}
